const express = require('express');
const cors = require('cors'); // enable cross origin resources sharing
const path = require('path'); // built-in to NodeJS, no need to npm install
require('dotenv').config();

const pool = require('./database');
const app = express();

// setup for the admin panel
app.set('view engine', 'ejs');
// __dirname: directory of that holds the current file
// path.join(__dirname, 'admin', 'views') => './admin/views'
// we use path.join so that we generate paths according to the machine's OS' specifications
app.set('views', path.join(__dirname, 'admin', 'views'));

// express.static -> refers where to find static resources
// any thing that is a file and not generated by Express is a static resource
// includes: css, js, image, json files
app.use('/admin/assets', express.static(
  path.join(__dirname, 'admin', 'public')  // =? ./admin/public
))

// enable cross origin resources sharing
app.use(cors());

// parse json bodies
// app.use(express.json());

// parse urlencoded bodies
app.use(express.urlencoded({ extended: true }));

// TODO: routes
const productRouter = require('./routes/products');
const userRouter = require('./routes/users');
const cartRouter = require('./routes/cart');
const checkoutRouter = require('./routes/checkout');
const stripeRouter = require('./routes/stripe');
const adminRouter = require('./admin/routes');

app.get('/health', async function(req,res){
  res.json({
    'message':"Working fine"
  })
})

// register the router
app.use('/api/products', express.json(), productRouter);
app.use('/api/users', express.json(), userRouter);
app.use('/api/cart', express.json(), cartRouter);
app.use('/api/checkout', express.json(), checkoutRouter);
app.use('/stripe', stripeRouter);
app.use('/admin', adminRouter);

const PORT = process.env.PORT || 3000;

app.listen(PORT, () => {
  console.log(`Server is running on port ${PORT}`);
});